language: "haskell"
install:
  - "cabal install"          # make sure it builds without -fdevel too!
  - "cabal install -fdevel"  # but we need -fdevel to run the tests
script: "fay-tests --plain"
notifications:
  irc:
    channels: "irc.freenode.net#fay"
    skip_join: true
  email: false
