language: "haskell"
install:
  - "cabal install 'happy >= 1.19'"
  - "travis_retry cabal install --force-reinstalls"
script: "scripts/travis-test"
notifications:
  irc:
    channels: "irc.freenode.net#fay"
    skip_join: true
  email:
    recipients:
      - adam@edea.se
    on_success: change
    on_failure: change
