language: "haskell"
install:
  - "travis_retry cabal install --force-reinstalls"
script: "scripts/travis-test"
notifications:
  irc:
    channels: "irc.freenode.net#fay"
    skip_join: true
  email: false
